"""make filename unique

Revision ID: 288823b358ea
Revises: 7aca146aa765
Create Date: 2026-08-28 10:43:35.393111

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "288823b358ea"
down_revision: Union[str, Sequence[str], None] = "7aca146aa765"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_unique_constraint("filename unique", ["filename"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_constraint("filename unique", type_="unique")

    # ### end Alembic commands ###
