"""filename no longer unique

Revision ID: e0f40be77d71
Revises: 288823b358ea
Create Date: 2026-10-04 14:34:33.040144

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0f40be77d71"
down_revision: Union[str, Sequence[str], None] = "288823b358ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("filename unique"), type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("filename unique"), ["filename"])

    # ### end Alembic commands ###
